src/objects/Course_Attendee__c.object
<CustomObject>
    <description>Used to track a student who attends a course.</description>
    <fields>
        <fullName>Course_Delivery__c</fullName>
        <description>Course delivery that student is attending.</description>
        <label>Course Delivery</label>
        <referenceTo>Course_Delivery__c</referenceTo>
        <relationshipLabel>Course Attendees</relationshipLabel>
        <relationshipName>Course_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>Contact who is attending the course delivery.</description>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Technician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Attendees</relationshipLabel>
        <relationshipName>Course_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Course Attendee</label>
    <nameField>
        <displayFormat>ATTENDEE-{00000}</displayFormat>
        <label>Course Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course_Delivery__c.object
<CustomObject>
    <description>Used to track each time a course is delivered.</description>
    <fields>
        <fullName>Instructor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Instructor that will teach a course.</description>
        <label>Instructor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Is_Instructor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Course_Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Delivery</label>
    <nameField>
        <displayFormat>DELIVERY-{00000}</displayFormat>
        <label>Course Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StudentBrowser.cls
public with sharing class StudentBrowser {
    @AuraEnabled
    public static List<Contact> getStudents(String courseDeliveryId, String instructorId){
        String query = 'SELECT Id, Name, Email, Phone, Title, Account.Name, PhotoUrl FROM Contact WHERE Name <> \'\'';
        
        if (courseDeliveryId != '') {
            query = query + ' AND Id IN (SELECT Student__c FROM course_attendee__c WHERE course_delivery__c = \'' + String.escapeSingleQuotes(courseDeliveryId) + '\')';
        } else if (instructorId != '') {
            query = query + ' AND Id IN (SELECT Student__c FROM course_attendee__c WHERE course_delivery__r.Instructor__c = \'' + String.escapeSingleQuotes(instructorId) + '\')';
        }
        
        query = query + ' ORDER BY Name';
        
        List<Contact> sobjList = Database.query(query);
        return sobjList;
    }
}