src/objects/Course_Delivery__c.object
<CustomObject>
    <description>Used to track each time a course is delivered.</description>
    <fields>
        <fullName>Attendee_Count__c</fullName>
        <label>Attendee Count</label>
        <summaryFilterItems>
            <field>Course_Attendee__c.Status__c</field>
            <operation>equals</operation>
            <value>Enrolled,Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Course_Attendee__c.Course_Delivery__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Instructor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Instructor that will teach a course.</description>
        <label>Instructor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Is_Instructor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Course_Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>City where a course will take place.</description>
        <label>Location</label>
        <picklist>
            <controllingField>Region__c</controllingField>
            <picklistValues>
                <fullName>Tokyo, JP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore, SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paris, FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London, GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Berlin, DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Francisco, US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chicago, US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toronto, CA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date the course will begin.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the course delivery.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course Delivery</label>
    <nameField>
        <displayFormat>DELIVERY-{00000}</displayFormat>
        <label>Course Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Is_Instructor__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether or not a user is an instructor. This field is used to filter user records when selecting the Instructor for a course delivery. It is also used to filter user records when selecting the Certifying Instructor for a certification attempt.</description>
        <inlineHelpText>Select this checkbox if the user is an instructor.</inlineHelpText>
        <label>Instructor?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/StudentBrowserForm.cls
public with sharing class StudentBrowserForm {
    @AuraEnabled
    public static List<User> getInstructors() {
         return [
            SELECT Id, Name
            FROM User
            WHERE Is_Instructor__c = true
            ORDER BY Name
        ];
    }
    @AuraEnabled
    public static List<Course_Delivery__c> getDeliveriesByInstructor(Id instructorId ) {
        return [
            SELECT Id, Start_Date__c, Location__c, Attendee_Count__c
            FROM Course_Delivery__c
            WHERE Instructor__c = :instructorId AND Status__c IN ('Enrolled','Completed','Delivered','Scheduled')
            ORDER BY Start_Date__c DESC
        ];
    }

}