src/objects/TripReport__c.object
<CustomObject>
    <description>Used in DEX601 Programming Lightning Components exercises.</description>
    <fields>
        <fullName>ReviewType__c</fullName>
        <label>ReviewType</label>
        <picklist>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restaurant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Students</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Trip Report</label>
    <nameField>
        <label>Trip Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TripReportForm.cls
public with sharing class TripReportForm {

    @AuraEnabled
    public static List<User> getInstructors() {
        return StudentBrowserForm.getInstructors();
    }

    @AuraEnabled
    public static List<String> getLocationTypes() {

        List <String> options = new list <String>();

        Schema.DescribeFieldResult fieldResult = TripReport__c.ReviewType__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

        for(Schema.PicklistEntry f : ple) {
            options.add(f.getLabel());
        }

        return options;
    }

}